const professorsData = [
    {
        name: "강경필",
        photo: "image/사진/강경필.jpg",
        field: "자연어처리, 데이터마이닝, 기계학습",
        lab: "공학6호관 502호",
        contact: "033-250-6389",
        email: "rudvlf0413@kangwon.ac.kr",
        specialties: ["자연어처리", "데이터마이닝", "기계학습"],
        description: "자연어 처리와 데이터 마이닝 분야의 전문가로, 텍스트 데이터 분석과 기계학습 기술을 활용한 연구를 진행하고 있습니다. 특히 한국어 자연어 처리 기술 개발에 집중하며, 실용적인 언어 모델 구축에 기여하고 있습니다.",
        papers: ["See, caption, cluster: Large-scale image analysis using captioning and topic modeling", "Restoring and Mining the Records of the Joseon Dynasty via Neural Language Modeling and Machine Translation", "Whose Opinion Matters? Analyzing Relationships Between Bitcoin Prices and User Groups in Online Community"]
    },
    {
        name: "김도형",
        photo: "image/사진/김도형.jpg",
        field: "컴퓨터네트워크, 미래인터넷 아키텍처, 머신러닝 기반 네트워킹",
        lab: "한빛관 403호",
        contact: "033-250-8445",
        email: "d.kim@kangwon.ac.kr",
        specialties: ["컴퓨터네트워크", "미래인터넷아키텍처", "머신러닝네트워킹"],
        description: "차세대 인터넷 아키텍처와 머신러닝 기반 네트워킹 기술 연구를 수행하고 있습니다. ICN(Information-Centric Networking) 기술과 지능형 네트워크 시스템 개발에 전문성을 가지고 있으며, 미래 네트워크 인프라 구축에 기여하고 있습니다.",
        papers: ["Design and Implementation of a Blockchain-Based Open Peer Review System Using Hyperledger Fabric", "Rescuing QUIC Flows from Countermeasures against UDP Floodig Attacks", "RepCoder: an automated program repair framework for probability-based program synthesis"]
    },
    {
        name: "김아욱",
        photo: "image/사진/김아욱.jpg",
        field: "인간-인공지능 상호작용, 모바일 컴퓨팅, 데이터사이언스",
        lab: "공학6호관 501호",
        contact: "033-250-6388",
        email: "kimauk@kangwon.ac.kr",
        specialties: ["인간AI상호작용", "모바일컴퓨팅", "데이터사이언스"],
        description: "인간과 인공지능의 상호작용 연구를 통해 사용자 친화적인 AI 시스템 개발에 집중하고 있습니다. 모바일 환경에서의 데이터 활용과 사용자 경험 개선을 위한 연구를 수행하며, HCI 분야의 혁신적인 솔루션을 제공하고 있습니다.",
        papers: ["Effects of in-vehicle auditory interactions on takeover performance in SAE L2 semi-automated vehicles", "Associations between Nicotine Dependence, Smartphone Usage Patterns, and Expected Compliance with a Smoking Cessation Application among Smokers", "Exploring Context-Aware Mental Health Self-Tracking Using Multimodal Smart Speakers in Home Environments"]
    },
    {
        name: "김용석",
        photo: "image/사진/김용석.gif",
        field: "운영체제, 임베디드 시스템 소프트웨어, 병렬처리 컴퓨터",
        lab: "공학6호관 408호",
        contact: "033-250-6384",
        email: "yskim@kangwon.ac.kr",
        specialties: ["운영체제", "임베디드시스템", "병렬처리"],
        description: "시스템 소프트웨어와 임베디드 시스템 분야의 전문가로, 효율적인 운영체제 설계와 병렬 처리 시스템 개발에 중점을 두고 있습니다. IoT 기기와 실시간 시스템을 위한 최적화된 소프트웨어 솔루션을 연구하고 있습니다.",
        papers: ["플래시 메모리 기반의 F2FS 파일시스템을 위한 인덱스 구조의 개선", "선박용 GPS 플로터의 위치정보 추출을 통한 항적 데이터 분석 방법", "대용량 SSD를 위한 다단계 플래시 변환계층"]
    },
    {
        name: "김윤",
        photo: "image/사진/김윤.jpg",
        field: "딥러닝, 컴퓨터비전, 의료영상분석",
        lab: "공학6호관 504호",
        contact: "033-250-6387",
        email: "yooni@kangwon.ac.kr",
        specialties: ["딥러닝", "컴퓨터비전", "의료영상분석"],
        description: "딥러닝과 컴퓨터 비전 기술을 활용한 의료 영상 분석 연구의 선두주자입니다. 의료진단 보조 시스템 개발과 영상 처리 알고리즘 최적화를 통해 헬스케어 분야의 AI 기술 발전에 기여하고 있습니다.",
        papers: ["Very fast, high-resolution aggregation 3D detection CAM to quickly and accurately find facial fracture areas", "Multi-modality multi-task model for mRS prediction using diffusion-weighted resonance imaging", "Deep Learning-Based Real-Time Organ Localization and Transit Time Estimation in Wireless Capsule Endoscopy"]
    },
    {
        name: "김종민",
        photo: "image/사진/김종민.jpg",
        field: "컴퓨터그래픽스, 가상현실, 기계학습, 수치최적화",
        lab: "공학6호관 507호",
        contact: "033-250-8447",
        email: "jongmin.kim@kangwon.ac.kr",
        specialties: ["컴퓨터그래픽스", "가상현실", "수치최적화"],
        description: "컴퓨터 그래픽스와 가상현실 기술의 전문가로, 몰입형 VR 환경 구축과 실시간 렌더링 기술 개발에 집중하고 있습니다. 기계학습을 활용한 그래픽스 최적화와 사용자 경험 향상을 위한 연구를 수행하고 있습니다.",
        papers: ["Anisotropic SpiralNet for 3D Shape Completion and Denoising", "Human motion reconstruction using deep transformer networks", "Robust methods for estimating the orientation and position of IMU and MARG sensors"]
    },
    {
        name: "문양세",
        photo: "image/사진/문양세.png",
        field: "데이터베이스, 데이터마이닝, 빅데이터 처리, 스마트 및 클라우드 컴퓨팅",
        lab: "한빛관 303호",
        contact: "033-250-8449",
        email: "ysmoon@kangwon.ac.kr",
        specialties: ["데이터베이스", "빅데이터처리", "클라우드컴퓨팅"],
        description: "대용량 데이터 처리와 클라우드 컴퓨팅 환경에서의 데이터베이스 최적화 연구를 선도하고 있습니다. 스마트 시티와 IoT 환경에서 생성되는 빅데이터의 효율적 관리와 분석 시스템 개발에 전문성을 가지고 있습니다.",
        papers: ["Domain Transformation to Graphs and GraphSAGE-Based Embedding for Performance Enhancement in Time-Series Classification", "쿠버네티스와 Ceph 환경을 활용한 GraphSAGE 분산 학습 프레임워크", "효율적인 학습 모델 버저닝을 지원하는 Kubernetes 기반 분산 빅데이터 처리 프레임워크"]
    },
    {
        name: "박연수",
        photo: "image/사진/박연수.jpg",
        field: "빅데이터, 데이터베이스",
        lab: "한빛관 407호",
        contact: "033-250-8446",
        email: "yeonsu.park@kangwon.ac.kr",
        specialties: ["빅데이터", "데이터베이스", "데이터분석"],
        description: "빅데이터 플랫폼과 분산 데이터베이스 시스템 전문가로, 대규모 데이터 처리 및 실시간 분석 기술 개발에 집중하고 있습니다. 데이터 중심의 의사결정 지원 시스템과 지능형 데이터 관리 솔루션을 연구하고 있습니다.",
        papers: ["QaaD (Query-as-a-Data): Scalable Execution of Massive Number of Small Queries in Spark", "G-CARE: A Framework for Performance Benchmarking of Cardinality Estimation Techniques for Subgraph Matching"]
    },
    {
        name: "박치현",
        photo: "image/사진/박치현.jpg",
        field: "생물정보학, 머신러닝, 데이터마이닝",
        lab: "한빛관 405호",
        contact: "033-250-8444",
        email: "chihyun@kangwon.ac.kr",
        specialties: ["생물정보학", "머신러닝", "바이오데이터분석"],
        description: "생명과학과 컴퓨터 과학의 융합 연구를 통해 생물정보학 분야를 선도하고 있습니다. 유전체 데이터 분석과 단백질 구조 예측을 위한 머신러닝 기법 개발에 집중하며, 정밀의학 발전에 기여하고 있습니다.",
        papers: ["KNU-DTI: KNowledge United Drug-Target Interaction prediction", "De novo drug design through gradient-based regularized search in information-theoretically controlled latent space", "DrDiff: Drug Response Prediction Through Controllable Diffusion-GE and Graph Attention Network"]
    },
    {
        name: "송원준",
        photo: "image/사진/송원준.jpg",
        field: "컴퓨터 아키텍처, 시스템 보안",
        lab: "공학6호관 506호",
        contact: "033-250-6392",
        email: "wjsong@kangwon.ac.kr",
        specialties: ["컴퓨터아키텍처", "시스템보안", "하드웨어보안"],
        description: "컴퓨터 시스템의 하드웨어 레벨 보안과 안전한 컴퓨터 아키텍처 설계 연구를 수행하고 있습니다. 사이드채널 공격 방어와 신뢰할 수 있는 컴퓨팅 환경 구축을 위한 혁신적인 보안 기술 개발에 전문성을 가지고 있습니다.",
        papers: ["DIMScern: A Framework for Discerning DIMSE Services on Remote Medical Devices", "Rescuing QUIC Flows from Countermeasures against UDP Floodig Attacks", "비 문서화 명령어 탐색 퍼저의 명령어 실행 정보 기반 길이 결정 방법"]
    },
    {
        name: "이구연",
        photo: "image/사진/이구연.jpg",
        field: "컴퓨터 네트워크, 데이터통신, 네트워크보안, 이동통신, 통신프로토콜",
        lab: "공학6호관 508호",
        contact: "033-250-6394",
        email: "leegyeon@kangwon.ac.kr",
        specialties: ["네트워크보안", "이동통신", "통신프로토콜"],
        description: "네트워크 통신과 보안 분야의 베테랑 연구자로, 안전하고 효율적인 통신 프로토콜 설계와 네트워크 보안 시스템 개발에 오랜 경험을 가지고 있습니다. 차세대 이동통신과 IoT 네트워크 보안 기술 연구를 수행하고 있습니다.",
        papers: ["허용 지연 시간을 갖는 실시간 화상 감시 카메라 시스템의 최적 구성 연구", "Dialogflow를 이용한 음성 기반 대화형 서비스", "다중 서비스 시스템에서의 효율적인 이용 순서"]
    },
    {
        name: "이다영",
        photo: "image/사진/이다영.jpg",
        field: "시스템 소프트웨어, 클라우드 시스템, 멀티미디어 시스템, 임베디드 시스템",
        lab: "공학6호관 403호",
        contact: "033-250-6393",
        email: "dayoung08@kangwon.ac.kr",
        specialties: ["클라우드시스템", "멀티미디어시스템", "시스템소프트웨어"],
        description: "클라우드 환경에서의 시스템 소프트웨어 최적화와 멀티미디어 처리 시스템 개발 전문가입니다. 분산 시스템과 임베디드 환경에서의 효율적인 자원 관리 및 성능 최적화 기술 연구에 집중하고 있습니다.",
        papers: ["Cost-Effective, Quality-Oriented Transcoding of Live-Streamed Video on Edge-Servers", "Video File Allocation for Wear-Leveling in Distributed Storage Systems With Heterogeneous Solid-State-Disks (SSDs)", "Quality-Aware Transcoding Task Allocation Under Limited Power in Live-Streaming Systems"]
    },
    {
        name: "이재권",
        photo: "image/사진/이재권.jpg",
        field: "소프트웨어 공학, 인공지능, 임베디드시스템, 기계학습",
        lab: "공학6호관 602호",
        contact: "033-250-6395",
        email: "jaekwon.lee@kangwon.ac.kr",
        specialties: ["소프트웨어공학", "인공지능", "임베디드AI"],
        description: "소프트웨어 공학 방법론과 AI 기술의 융합 연구를 통해 지능형 소프트웨어 개발 프로세스를 혁신하고 있습니다. 임베디드 시스템에서의 AI 활용과 자동화된 소프트웨어 개발 도구 연구에 전문성을 가지고 있습니다.",
        papers: ["Probabilistic Safe WCET Estimation for Weakly Hard Real-time Systems at Design Stages", "Fuzzing for CPS Mutation Testing", "Optimal priority assignment for real-time systems: a coevolution-based approach"]
    },
    {
        name: "이창기",
        photo: "image/사진/이창기.jpg",
        field: "자연언어처리, 정보검색, 기계학습",
        lab: "한빛관 301호",
        contact: "033-250-8443",
        email: "leeck@kangwon.ac.kr",
        specialties: ["자연언어처리", "정보검색", "텍스트마이닝"],
        description: "자연어 처리와 정보 검색 기술의 전문가로, 대용량 텍스트 데이터에서 의미 있는 정보를 추출하고 검색하는 시스템 개발에 집중하고 있습니다. 한국어 정보 검색 성능 향상과 지능형 검색 엔진 구축 연구를 수행하고 있습니다.",
        papers: ["형태소 수준의 BERT 임베딩을 통한 한국어 상호참조해결", "군집 알고리즘과 NSP를 이용한 문서 단위 기계 번역 데이터 증강", "문서 단위 기계 번역 성능 향상을 위한 데이터 증강 기법"]
    },
    {
        name: "이헌길",
        photo: "image/사진/이헌길.gif",
        field: "분산처리, 무선 센서 네트워크, 컴퓨터 보안",
        lab: "공학6호관 405호",
        contact: "033-250-6385",
        email: "hglee@kangwon.ac.kr",
        specialties: ["분산처리", "센서네트워크", "네트워크보안"],
        description: "분산 컴퓨팅과 무선 센서 네트워크 분야의 전문가로, IoT 환경에서의 효율적인 데이터 처리와 보안 기술 개발에 집중하고 있습니다. 대규모 분산 시스템의 안정성과 보안성 향상을 위한 연구를 수행하고 있습니다.",
        papers: ["Adaptive Square-Shaped Trajectory-Based Service Location Protocol in Wireless Sensor Networks", "제한된 자원의 무선 단말기를 위한 종단간 보안을 제공하는 WTLSW프로토콜 및 프록시 모델", "센서네트워크에서의 프록시 트라젝토리 기반 데이터 저장 기법"]
    },
    {
        name: "임현승",
        photo: "image/사진/임현승.png",
        field: "프로그래밍 언어, 인공지능/기계학습/딥러닝, 의료인공지능",
        lab: "한빛관 307호",
        contact: "033-250-8441",
        email: "hsim@kangwon.ac.kr",
        specialties: ["프로그래밍언어", "의료AI", "딥러닝"],
        description: "프로그래밍 언어 이론과 의료 인공지능의 융합 연구를 선도하고 있습니다. 안전하고 효율적인 프로그래밍 언어 설계와 의료 데이터 분석을 위한 딥러닝 기술 개발에 전문성을 가지고 있으며, 헬스케어 AI 솔루션 구축에 기여하고 있습니다.",
        papers: ["단일 리드 심전도 데이터를 이용한 심혈관 질환 예측", "Medical Data Analysis Using AutoML Frameworks", "Predicting the Progression of Mild Cognitive Impairment to Alzheimer's Dementia Using Recurrent Neural Networks With a Series of Neuropsychological Tests"]
    },
    {
        name: "정인범",
        photo: "image/사진/정인범.jpg",
        field: "운영체제, 소프트웨어 공학, 임베디드 시스템, 사물 인터넷(IOT)",
        lab: "공학6호관 505호",
        contact: "033-250-6396",
        email: "ibjung@kangwon.ac.kr",
        specialties: ["운영체제", "IoT시스템", "임베디드소프트웨어"],
        description: "IoT와 임베디드 시스템을 위한 운영체제 및 소프트웨어 아키텍처 연구의 전문가입니다. 스마트 환경에서의 효율적인 자원 관리와 실시간 시스템 최적화를 통해 차세대 IoT 플랫폼 개발에 기여하고 있습니다.",
        papers: ["라이다 기반 실내 자율주행 차량에서 신경망 학습을 사용한 성능평가", "Neural Network Models for Driving Control of Indoor Autonomous Vehicles in Mobile Edge Computing", "Smart Parking Lot Based on Edge Cluster Computing for Full Self-Driving Vehicles"]
    },
    {
        name: "최미정",
        photo: "image/사진/최미정.jpg",
        field: "네트워크 트래픽 측정 및 분석, M2M 네트워크 및 서비스 자율 관리, 모바일 트래픽 비정상 행위 탐지 및 분석",
        lab: "한빛관 305호",
        contact: "033-250-8442",
        email: "mjchoi@kangwon.ac.kr",
        specialties: ["네트워크트래픽분석", "M2M통신", "이상행위탐지"],
        description: "네트워크 트래픽 분석과 이상 행위 탐지 분야의 전문가로, M2M 통신과 모바일 네트워크의 자율적 관리 시스템 개발에 집중하고 있습니다. 지능형 네트워크 모니터링과 보안 위협 탐지 기술 연구를 수행하고 있습니다.",
        papers: ["머신 러닝을 활용한 스마트 컨트랙트 취약점 탐지 연구 동향", "바이너리 파일에서 사용된 오픈소스 소프트웨어 재사용 탐지 연구", "바이너리 파일에서 SBOM 생성을 위한 오픈소스 소프트웨어 재사용 탐지 아키텍처"]
    },
    {
        name: "최우혁",
        photo: "image/사진/최우혁.jpg",
        field: "디지털 헬스, 센서 데이터 사이언스, 인간-인공지능 상호작용",
        lab: "공학6호관 407호",
        contact: "033-250-6391",
        email: "woohyeok.choi@kangwon.ac.kr",
        specialties: ["디지털헬스", "센서데이터분석", "헬스케어AI"],
        description: "디지털 헬스케어와 웨어러블 센서 데이터 분석 전문가로, 개인화된 건강 관리 시스템과 예방 의학을 위한 AI 기술 개발에 집중하고 있습니다. 인간 중심의 헬스케어 AI 솔루션 구축을 통해 삶의 질 향상에 기여하고 있습니다.",
        papers: ["Effects of in-vehicle auditory interactions on takeover performance in SAE L2 semi-automated vehicles", "FamilyScope: Visualizing Affective Aspects of Family Social Interactions using Passive Sensor Data", "K-EmoPhone: A Mobile and Wearable Dataset with In-Situ Emotion, Stress, and Attention Labels"]
    },
    {
        name: "최황규",
        photo: "image/사진/최황규.gif",
        field: "데이터베이스 시스템, 클라우드 컴퓨팅, 빅데이터",
        lab: "공학6호관 404호",
        contact: "033-250-6382",
        email: "hkchoi@kangwon.ac.kr",
        specialties: ["데이터베이스시스템", "클라우드컴퓨팅", "분산데이터베이스"],
        description: "대용량 데이터베이스 시스템과 클라우드 환경에서의 데이터 관리 기술 전문가입니다. 분산 데이터베이스 최적화와 클라우드 기반 빅데이터 처리 플랫폼 개발을 통해 차세대 데이터 인프라 구축에 기여하고 있습니다.",
        papers: ["전기차 충전설비에 있어서 도로교통량 데이터를 기반으로 한 충전수요예측 모델 연구", "A Study on the Improvement of Electrified Railway Inducing Voltage Calculation Algorithm", "원-핫 인코딩을 이용한 딥러닝 단기 전력수요 예측모델"]
    },
    {
        name: "하진영",
        photo: "image/사진/하진영.jpeg",
        field: "패턴인식, 인공지능, HCI",
        lab: "공학6호관 406호",
        contact: "033-250-6386",
        email: "jyha@kangwon.ac.kr",
        specialties: ["패턴인식", "인공지능", "인간컴퓨터상호작용"],
        description: "패턴 인식과 인공지능 기술을 활용한 HCI 시스템 개발의 전문가입니다. 사용자의 행동 패턴 분석과 지능형 인터페이스 설계를 통해 직관적이고 효율적인 인간-컴퓨터 상호작용 환경 구축에 집중하고 있습니다.",
        papers: ["공공 자전거 수요 예측을 위한 사이킷런의 지도 기계 학습 모델 성능 비교", "공공자전거 이용 현황 데이터 분석 및 시각화", "텐서플로를 이용한 온라인 쇼핑몰 카테고리 자동화 시스템 구축"]
    },
    {
        name: "김우주",
        photo: "image/사진/김우주.jpg",
        field: "인간공학, 가상·증강현실, 3D 사용자 인터페이스",
        lab: "60주년 기념관 203-1호",
        contact: "033-250-7653",
        email: "woojoo.kim@kangwon.ac.kr",
        specialties: ["인간공학", "가상증강현실", "3D인터페이스"],
        description: "인간공학과 메타버스 기술의 전문가로, 가상현실과 증강현실 환경에서의 3D 사용자 인터페이스 설계에 집중하고 있습니다. 사용자 경험 최적화와 몰입형 인터랙션 기술 개발을 통해 차세대 메타버스 플랫폼 구축에 기여하고 있습니다.",
        papers: ["Revisiting sensor-based intelligent fall risk assessment for older people: A systematic review", "TouchView: Mid-Air Touch on Zoomable 2D View for Distant Freehand Selection on a Virtual Reality User Interface", "Pseudo-haptic button for improving user experience of mid-air interaction in VR"]
    },
    {
        name: "손경호",
        photo: "image/사진/손경호.jpg",
        field: "사이버보안, IoT-융합보안, 정보보호시스템 개발, 개인정보보호",
        lab: "한빛관 206호",
        contact: "033-250-7204",
        email: "khson@kangwon.ac.kr",
        specialties: ["사이버보안", "IoT보안", "개인정보보호"],
        description: "사이버보안과 IoT 융합보안 분야의 전문가로, 차세대 정보보호 시스템 개발과 개인정보보호 기술 연구에 집중하고 있습니다. 스마트 환경에서의 종합적인 보안 솔루션 구축과 정보보증 기술 개발에 전문성을 가지고 있습니다.",
        papers: ["Endpoint Device Risk-Scoring Algorithm Proposal for Zero Trust", "MyData Personal Data Store Model(PDS) to Enhance Information Security for Guarantee the Self-determination rights", "제로 트러스트(Zero-Trust) 기반의 스마트시티 공급망 보안 모델 연구"]
    },
    {
        name: "이동재",
        photo: "image/사진/이동재.jpg",
        field: "암호학, 양자 컴퓨팅, 융합보안",
        lab: "미정",
        contact: "033-250-7980",
        email: "dongjae.lee@kangwon.ac.kr",
        specialties: ["암호학", "양자컴퓨팅"],
        description: "융합보안 분야의 전문가로, 다양한 IT 환경에서의 통합 보안 솔루션 개발에 집중하고 있습니다. 신기술과 보안의 융합을 통한 혁신적인 보안 체계 구축 연구를 수행하고 있습니다.",
        papers: ["Improved Quantum Rebound Attacks on Double Block Length Hashing with Round-Reduced AES-256 and ARIA-256", "Accurate False-Positive Probability of Multiset-Based Demirci-Selçuk Meet-in-the-Middle Attacks", "A Practical Ciphertext-Only Attack on GMR-2 System"]
    },
    {
        name: "이병기",
        photo: "image/사진/이병기.png",
        field: "의료빅데이터, 의료정보표준",
        lab: "한빛관 208호",
        contact: "033-250-7672",
        email: "bkyi@kangwon.ac.kr",
        specialties: ["의료빅데이터", "의료정보표준", "헬스케어정보학"],
        description: "의료 빅데이터와 의료정보 표준화 분야의 전문가로, 헬스케어 데이터의 체계적 관리와 분석 시스템 개발에 집중하고 있습니다. 의료정보 표준화를 통한 상호운용성 향상과 데이터 기반 의료 서비스 혁신에 기여하고 있습니다.",
        papers: ["Status of MyHealthWay and Suggestions for Widespread Implementation, Emphasizing the Utilization and Practical Use of Personal Medical Data", "Deep learning approach to detection of colonoscopic information from unstructured reports", "Shared Interoperable Clinical Decision Support Service for Drug-Allergy Interaction Checks: Implementation Study"]
    },
    {
        name: "이세영",
        photo: "image/사진/이세영.jpg",
        field: "융합보안, CPS보안, IoT보안, 센서보안",
        lab: "미정",
        contact: "033-250-7974",
        email: "seyoung@kangwon.ac.kr",
        specialties: ["CPS보안", "IoT보안", "센서보안"],
        description: "융합보안 분야의 연구자로, 다학제간 융합을 통한 보안 기술 개발에 집중하고 있습니다. 새로운 보안 위협에 대응하는 혁신적인 보안 솔루션 연구를 수행하고 있습니다.",
        papers: ["DIMScern: A Framework for Discerning DIMSE Services on Remote Medical Devices", "In-Vehicle Network Intrusion Detection System Using CAN Frame-Aware Features", "ErrIDS: An Enhanced Cumulative Timing Error-Based Automotive Intrusion Detection System"]
    },
    {
        name: "이효준",
        photo: "image/사진/이효준.jpg",
        field: "컴퓨터비전, 영상처리, 딥러닝",
        lab: "한빛관 207호",
        contact: "033-250-7671",
        email: "gywns6298@kangwon.ac.kr",
        specialties: ["컴퓨터비전", "영상처리", "딥러닝"],
        description: "컴퓨터 비전과 딥러닝 기술의 전문가로, 고도화된 영상 처리 알고리즘과 시각 인식 시스템 개발에 집중하고 있습니다. AI 기반 영상 분석 기술을 통해 다양한 응용 분야에서의 지능형 시스템 구축에 기여하고 있습니다.",
        papers: ["Joint Appearance and Motion Model With Temporal Transformer for Multiple Object Tracking", "deepGBLUP: joint deep learning networks and GBLUP framework for accurate genomic prediction of complex traits in Korean native cattle", "BAAM: Monocular 3D Pose and Shape Reconstruction With Bi-Contextual Attention Module and Attention-Guided Modeling"]
    },
    {
        name: "임정욱",
        photo: "image/사진/임정욱.png",
        field: "인간-컴퓨터 상호작용, 빅데이터분석, 학습분석",
        lab: "한빛관 205호",
        contact: "033-250-7673",
        email: "rhim8668@kangwon.ac.kr",
        specialties: ["HCI", "빅데이터분석", "학습분석"],
        description: "인간-컴퓨터 상호작용과 교육 데이터 분석 분야의 전문가로, 학습자 행동 분석과 개인화된 학습 시스템 개발에 집중하고 있습니다. 빅데이터 기술을 활용한 지능형 교육 플랫폼 구축과 학습 효과 향상 연구를 수행하고 있습니다.",
        papers: ["Using Geometric Features of Drag-and-Drop Trajectories to Understand Students' Learning", "Application of humanization to survey chatbots: Change in chatbot perception, interaction experience, and survey data quality"]
    }
];

function getFieldDisplayName(fieldValue) {
    const fieldMap = {
        "전자공학": "전자공학",
        "컴퓨터구조론": "컴퓨터 구조론", 
        "신호처리제어": "신호 처리 및 제어",
        "임베디드컴퓨팅": "임베디드 컴퓨팅 / 마이크로프로세서(CPU)",
        "컴퓨터하드웨어응용": "컴퓨터 하드웨어 응용",
        "소프트웨어개발방법론": "소프트웨어 개발방법론",
        "계산과학": "계산과학",
        "컴퓨터그래픽스": "컴퓨터 그래픽스",
        "운영체제": "운영체제",
        "데이터베이스": "데이터베이스", 
        "통신컴퓨터네트워크": "통신 및 컴퓨터 네트워크",
        "정보보안": "정보보안",
        "암호학": "암호학",
        "인공지능신경과학": "인공지능, 신경과학",
        "자연어처리": "자연어 처리",
        "코딩": "코딩",
        "금융공학": "금융공학",
        "HCI": "HCI (인간-컴퓨터 상호작용)",
        "머신러닝": "머신러닝",
        "딥러닝": "딥러닝",
        "데이터사이언스": "데이터사이언스",
        "빅데이터": "빅데이터",
        "소프트웨어공학": "소프트웨어공학",
        "임베디드시스템": "임베디드시스템",
        "프로그래밍언어": "프로그래밍언어",
        "시스템소프트웨어": "시스템소프트웨어"
    };
    
    return fieldMap[fieldValue] || fieldValue;
} 