version: "3.9"

services:
  frontend:
    image: ${DOCKER_NAMESPACE}/yideunandhyeonjun-frontend:${TAG:-latest}
    container_name: yideunandhyeonjun-frontend
    build:
      context: ../../../
      dockerfile: deploy/deploy-test-server/dev/frontend.Dockerfile
    ports:
      - "8080:80"